### ISSUE TITLE
Possible Incorrect Syntax in Event Bridge Transform Docs

### ISSUE THREAD

**Issue by Spencer-Doak** [awsdocs/amazon-eventbridge-user-guide#25]
Hi, there! I happened to be browsing AWS' documentation about Event Bridge transformations, and I noticed what appears to be an incorrect example. The input template example labeled "Amazon CloudWatch log group" shows output that is invalid JSON. The output has an unclosed string and the resultant object is closed by a right parenthesis (`)`) instead of a right brace (`}`). Furthermore, the output contains unescaped double quotes around the instance ID. I just want to bring this possible mistake to your attention or verify whether this is the correct/intended output.

The line in question can be found here:

https://github.com/awsdocs/amazon-eventbridge-user-guide/blob/10e936eebdd8b9ea9f5670e316e11bddada84aca/doc_source/eb-transform-target-input.md?plain=1#L72

The page in AWS's documentation can be found here:

https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-transform-target-input.html#eb-transform-input-examples

**Comment by kinclay** [comment]
Thanks for bringing this to our attention, I'll look into it soon.

**Comment by kinclay** [comment]
I have fixed this.
