### ISSUE TITLE
Filtering on nested fields doesnt work

### ISSUE THREAD

**Issue by digitalkaoz** [awsdocs/amazon-eventbridge-user-guide#27]
as stated in the docs it should be possible to filter on nested fields:

https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns.html (value matching)

1. Sample Event

```json
{
  "version": "0",
  "id": "4cb1378f-3e1a-1c32-f5d9-832b2fd53d8a",
  "detail-type": "SomeEventType",
  "source": "some.source",
  "account": "111",
  "time": "2022-05-16T08:29:16Z",
  "region": "eu-central-1",
  "resources": [],
  "detail": {
    "attributes": {
      "some_attribute": {
        // ...
      }
    }
  }
}
```

2. Event-Filter

```json
{
  "detail": {
    "attributes": {
      "some_attribute": [{
        "exists": true
      }]
    }
  }
}
```

The Test Tool always says:

`Sample event did not match the event pattern.`

**Comment by kinclay** [comment]
Thanks for pointing this out, I'll look into it.

**Comment by kinclay** [comment]
@digitalkoaz, I think I found the issue. In our docs we say "Exists matching only works on leaf nodes. It does not work on intermediate nodes." which basically means we can't value match against objects, just arrays, strings, etc. I edited your event as shown, changing "some_attribute" to a string and it matched. Let me know if you have more questions.

{
  "version": "0",
  "id": "4cb1378f-3e1a-1c32-f5d9-832b2fd53d8a",
  "detail-type": "SomeEventType",
  "source": "some.source",
  "account": "111",
  "time": "2022-05-16T08:29:16Z",
  "region": "eu-central-1",
  "resources": [],
  "detail": {
    "attributes": {
      "some_attribute": ""
    }
  }
}

**Comment by digitalkaoz** [comment]
To be honest, that doesnt solve the problem et all. I even tried `anything-but` doesnt work either. So how to check for existence of intermediate nodes?

**Comment by digitalkaoz** [comment]
and its not found in the docs too, you still say it should work (from the docs):

```json
// event
{
  "version": "0",
  "id": "0948ba87-d3b8-c6d4-f2da-732a1example",
  "detail-type": "Macie Finding",
  "source": "aws.macie",
  "account": "123456789012",
  "time": "2021-04-29T23:12:15Z",
  "region":"us-east-1",
  "resources": [

  ],
  "detail": {
    "schemaVersion": "1.0",
    "id": "64b917aa-3843-014c-91d8-937ffexample",
    "accountId": "123456789012",
    "partition": "aws",
    "region": "us-east-1",
    "type": "Policy:IAMUser/S3BucketEncryptionDisabled",
    "title": "Encryption is disabled for the S3 bucket",
    "description": "Encryption is disabled for the Amazon S3 bucket. The data in the bucket isn’t encrypted 
        using server-side encryption.",
    "severity": {
        "score": 1,
        "description": "Low"
    },
    "createdAt": "2021-04-29T15:46:02Z",
    "updatedAt": "2021-04-29T23:12:15Z",
    "count": 2
}
```

```json
//rule
{
  "source": ["aws.macie"],
  "detail-type": ["Macie Finding"],
  "detail": {
    "severity": {
      "score": [1]
    },
    "count":[2]
  }
}
```

so please @kinclay reopen the ticket, and investigate the problem please.
