### ISSUE TITLE
Cannot find the event payload description for scheduled events in eb-create-rule-schedule.md

### ISSUE THREAD

**Issue by canatella** [awsdocs/amazon-eventbridge-user-guide#32]
I looked at the doc but I can't seem to find the specification of the event payload received when using a cron rule.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
